all:
	cd gtests; make -j
	#cd gtests-interactive; make

check-style:
	cd gtests; make check-style

check-style-cse:
	cd gtests; make check-style-cse

clean:
	cd gtests; make clean
	#cd gtests-interactive; make clean
